Addons route
tli-group-4-grimm/backend pull request #69
Opened 2021-11-21 23:52 UTC by Mogtaba-Alim

Created addons route to allow the addons of the car to be fetched when a car is chosen by the user.
Created AttributizeCarAndIdUseCase to convert the coveted response type into an attribute map that can be packaged into a json.
Created GenerateIdUseCase to genernate an if from the given attribute map.
Changed in database fetcher to fetch a car with its id.
Changed in search to send an array of objects containing the id and car info of a car matching the searhc string.
Modified tests to adhere to these changes.
Created tests for AttributizeCarAndIdUseCase and GenerateIdUseCase.
Closes #68.
Closes #61

2021-11-22 00:17 UTC, mtoohey31 requested changes
Just a couple notes, looks good overall though!

2021-11-22 00:17 UTC, mtoohey31 commented on src/main/java/entitypackagers/AttributizeCarIDUseCase.java
> +                EntityStringNames.CAR_STRING,
I'm not completely sure, but should we use a different constant here, since this same constant is used in other places?

2021-11-22 00:17 UTC, mtoohey31 commented on src/main/java/fetchers/DataBaseFetcher.java
> +                Car car = (Car) extractCarArray(rs)[1];
I'm not sure if indexing the result of the `extractCarArray` method is the most efficient way to do this, should we maybe break the creation of that value into a separate method that can also be called by `extractCarArray`, and then we can call that method from here too?

2021-11-22 00:17 UTC, mtoohey31 commented on src/main/java/entitypackagers/GenerateIdUseCase.java
> +        DoubleAttribute idAttribute = (DoubleAttribute) map.getItem(EntityStringNames.ID_STRING);
I don't think this should be a double attribute, because doubles are floats but our ID's are integers.

2021-11-22 02:47 UTC, Mogtaba-Alim commented on src/main/java/entitypackagers/AttributizeCarIDUseCase.java
> +                EntityStringNames.CAR_STRING,
Ok changed

2021-11-23 20:55 UTC, RayanAlim approved these changes
Lgtm

2021-11-23 21:08 UTC, RayanAlim approved these changes
lgtm

2021-11-23 21:08 UTC, RayanAlim approved these changes

2021-11-23 21:58 UTC, Mogtaba-Alim commented on src/main/java/fetchers/DataBaseFetcher.java
> +                Car car = (Car) extractCarArray(rs)[1];
Created methods that address this issue

2021-11-23 21:59 UTC, Mogtaba-Alim commented on src/main/java/entitypackagers/GenerateIdUseCase.java
> +        DoubleAttribute idAttribute = (DoubleAttribute) map.getItem(EntityStringNames.ID_STRING);
The current parsers only return Numbers from JSON which are defaulted to doubles, so it is cast to int later

2021-11-23 23:19 UTC, closed without merging