Data population
tli-group-4-grimm/backend pull request #70
Opened 2021-11-23 21:33 UTC by RayanAlim

- Populated Car.csv
- Each car has an ID
- Created addons.csv and populated it 
- Each car id in cars.csv corresponds to an id in addons.csv to be used to add cars and their addons.

2021-11-24 03:23 UTC, mtoohey31 requested changes
Looks really great, nice job finding this dataset! There's just a few changes that would be good so the format works with our current implementation, if that's ok.

2021-11-24 03:23 UTC, mtoohey31 commented on data/addons.csv
> +id,Addons
Ideally, this csv should have the header:

```csv
id,name,price,description,vehicleId
```

Or something like that, so it matches the arrangement of the table in the `DataBaseFetcher`. We could also discussion storing [arrays](https://www.postgresql.org/docs/9.1/arrays.html) of related vehicleIds instead of having to duplicate, that might be a good idea but it will require some changes to #71.

2021-11-24 03:23 UTC, mtoohey31 commented on data/addons.csv
> +id,Addons
Just realized I merged addons as part of the cars csv originally in a similar format, so my bad there...

2021-11-24 03:23 UTC, mtoohey31 commented on data/cars.csv
> +kilometres,make,model,Year,Price,id
This looks awesome! Having more than 9 cars will make our demos so much better :smile:, the only thing I was wondering with this file is whether you could rearrange the headers so that they're in a similar order to last time, such as:

```csv
id,kilometers,make,model,Year,Price
```

Because our implementation depends on them being in that specific order.

2021-11-24 16:32 UTC, RayanAlim commented on data/cars.csv
> +kilometres,make,model,Year,Price,id
done

2021-11-24 16:36 UTC, RayanAlim commented on data/cars.csv
> +kilometres,make,model,Year,Price,id
Actually, if the Addons has an "vehicleID" column, shouldn't we also name the id column in cars.csv that instead of just "id"?

2021-11-25 04:30 UTC, RayanAlim commented on data/addons.csv
> +id,Addons
Done

2021-11-25 04:32 UTC, RayanAlim reviewed
done

2021-11-28 02:00 UTC, mtoohey31 approved these changes
Looks great, thank you for making those changes!

2021-11-28 02:00 UTC, merged